gimnasio/app/Http/routes.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
/*
|--------------------------------------------------------------------------
| Ruta para cerrar session
|--------------------------------------------------------------------------
|
*/
Route::get('logout', ['middleware' => 'auth', function()
{	
	Session::flush();
	clearstatcache();	
    Auth::logout();
	return Redirect::to('/')->with('flash_info', 'Se ha cerrado la sesión del usuario');
}]);

Route::get('/password/email', ['', function()
{	

	return view('auth.password');
}]);






Route::get('/helEmail', ['', function()
{	

	$data =[
		"title"=>"something",
		"content" =>  "somthing too",

	];


			Mail::send('emails.welcome',$data,function($message)
			{
				$message->to('stevengs_alfaro@hotmail.com', "Andrey");
				
				$message->from('gimnaciofitnesscenter@gmail.com');
				
				$message->subject("somthing");

			});

}]);








/*
|--------------------------------------------------------------------------
| Rutas para el controlador auth
|--------------------------------------------------------------------------
|
*/
Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


/*
|--------------------------------------------------------------------------
| Rutas para el controlador home
|--------------------------------------------------------------------------
|
*/
Route::get('home', ['middleware' => ['auth'], 'uses' => 'HomeController@index']);
//Route::get('home','HomeController@index');

//Route::get('prueba', ['middleware' => 'auth', 'uses' => 'HomeController@pruebas']);
Route::get('prueba', ['middleware' => 'auth', 'uses' => 'HomeController@consulta']);
//Route::get('prueba', ['uses' => 'HomeController@prueba']);
//Route::get('/prueba','HomeController@prueba');
//Route::get('/prueba10','HomeController@prueba10');

Route::get('/entre', ['middleware' => 'auth', function()
{	
	echo "si";
}]);

Route::get('/ok', ['middleware' => 'auth', function()
{	
	echo "si";
}]);


Route::get('/correos', ['middleware' => ['auth','is_admin'], 'uses' => 'HomeController@verCorreos']);
Route::post('/sendEmail', ['middleware' => ['auth','is_admin'], 'uses' => 'HomeController@sendEmail']);

Route::post('emailAllUsers', ['middleware' => ['auth','is_admin'],  'uses' => 'HomeController@emailAllUsers']);


/*
|--------------------------------------------------------------------------
| Rutas para el controlador Welcome
|--------------------------------------------------------------------------
|
*/
Route::get('/', ['middleware' => 'guest', 'uses' => 'WelcomeController@index']);


/*
|--------------------------------------------------------------------------
| Rutas del usuarios administrador
|--------------------------------------------------------------------------
|
| Aqui se encuentras las rutas que el administrdor va a usar en el sistema
|
*/
Route::group(['prefix' => 'admin', 'middleware' => ['auth','is_admin'], 'namespace' => 'Admin'],function(){

	Route::resource('users','UsersController');

});
Route::get('perfil/{id}', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@routePerfil']);

Route::post('editarImagen', ['middleware' => ['auth'],  'uses' => 'Admin\UsersController@editarImagen']);

Route::post('crearCita', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@getAjaxUsuario']);

Route::post('getAjaxUser', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@getAjaxUsuarioById']);

Route::post('saveDatosPago', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@ajaxSaveDatosPago']);

Route::post('getAjaxUsersByPayDay', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@getAjaxUsersByPayDay']);

Route::post('getUsersByName', ['middleware' => ['auth','is_admin'],  'uses' => 'Admin\UsersController@buscarUsarioPorNombre']);




/*
|--------------------------------------------------------------------------
| Rutas del usuarios medicion
|--------------------------------------------------------------------------
|
| Aqui se encuentras las rutasal controlador MedicionController que el administrdor va a usar en el sistema
|
*/

Route::group(['prefix' => 'medicion', 'middleware' => ['auth','is_admin'], 'namespace' => 'Medicion'],function(){

	Route::resource('medicion','MedicionController');

});

Route::get('medicion/{id}', ['middleware' => ['auth','is_admin'],  'uses' => 'Medicion\MedicionController@index']);
Route::post('saveIndice', ['middleware' => ['auth','is_admin'],  'uses' => 'Medicion\MedicionController@storeIndiceMasaCorporal']);
Route::post('saveFrecuencia', ['middleware' => ['auth','is_admin'],  'uses' => 'Medicion\MedicionController@storeFrecuenciaCardiaca']);




/*
|--------------------------------------------------------------------------
| Rutas del usuarios padecimientos
|--------------------------------------------------------------------------
|
| Aqui se encuentras las rutasal controlador PadecimientosController que el administrdor va a usar en el sistema
|
*/
Route::post('padecimiento', ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@store']);
Route::post('editarpadecimiento', ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@edit']);
Route::get('editarpadecimiento', ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@edit']);
//Route::post('/updatePadeciento', ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@update2']);
Route::post('/updatePadeciento', ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@update']);
//Route::get('editar' ['middleware' => ['auth','is_admin'],  'uses' => 'Padecimientos\PadecimientoController@store']);



/*
|--------------------------------------------------------------------------
| Rutas de CitaController
|--------------------------------------------------------------------------
|
| Aqui se encuentras las rutas al controlador CitaController que el administrdor va a usar en el sistema
|
*/
Route::group(['prefix' => 'cita', 'middleware' => ['auth','is_admin'], 'namespace' => 'Cita'],function(){

	Route::resource('cita','CitaController');

});
Route::get('getCitas', ['middleware' => ['auth','is_admin'],  'uses' => 'Cita\CitaController@verCitas']);
Route::post('updateEstado', ['middleware' => ['auth','is_admin'],  'uses' => 'Cita\CitaController@editatEstado']);

/*
|--------------------------------------------------------------------------
| Rutas del Pagos
|--------------------------------------------------------------------------
|
| Aqui se encuentras las rutasal controlador PagosController que el administrdor va a usar en el sistema
|
*/

Route::group(['prefix' => 'pagos', 'middleware' => ['auth','is_admin'], 'namespace' => 'Pagos'],function(){

	Route::resource('pagos','PagosController');

});
Route::get('/reportes', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@index']);
Route::get('/pagos/{id}', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@create']);
Route::get('/realizarPago', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@realizarPago']);
Route::get('/morosos', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@getMorosos']);
Route::get('/aldia', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@getAlDia']);
Route::get('/ingresos', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@showIngresos']);

Route::get('/ingresoHoy', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@getAjaxTodayIngresos']);
Route::post('/ingresoHoy', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@getAjaxTodayIngresos']);



Route::post('/getAjaxIngresos', ['middleware' => ['auth','is_admin'],  'uses' => 'Pagos\PagosController@getAjaxRangoIngresos']);



Route::get('/nada', function()
{	

	$queue = Queue::push(new \SendEmail($message));
	return	$queue;
});


class LogMessage
{
	public function fire(){
		return "hola";
	}
}

gimnasio/resources/views/partials/cita.blade.php
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" rel="stylesheet">
	<link href="https://raw.githubusercontent.com/Eonasdan/bootstrap-datetimepicker/master/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/admin_user/css/bootstrap-datetimepicker.min.css') }}" />
    
    <div class="citaContent">
    	<h3><p>Crear una cita</p></h3>
    	<br/>
    	{!! Form::open(array('url' => 'crearCita','role'=>'form','method' => 'POST','id'=>'btn-cita')) !!}
    		<h3>{!! Form::label('entrenador', 'Numero de Cédula',
								array('class' => 'control-label')) 
				!!}</h3>
    		<input type="text" id="cedula" name="cedula" maxlength="9" class="form-control" placeholder="Digite la cédula del usuario">
		{!! Form::close() !!}
		<br/>
		@include('admin.partials.messagesErrors')
    	{!! Form::open(['route' => ['cita.cita.store'],'method' => 'POST']) !!}
    	
    		<div class="maybeUsers">

			</div>
    		<div class="from-group">
				<div class="divficha">
					<h3>{!! Form::label('fecha_cita', 'Dia de la cita',
									array('class' => 'control-label')) 
					!!}</h3>
					<div class='input-group date' id='datetimepicker7'>
						{!! Form::text('fecha_inicio', null,['maxlength'=>'20','minlength'=>'4','class' => 'form-control','id' => 'txt_fecha_nacimiento','placeholder'=>'Fecha de Nacimiento', 'required'  ])!!}
						<span class="input-group-addon date2" >
		    				<span class="glyphicon glyphicon-calendar calendarFecha"></span>
		    			</span>
		    		</div>
	    		</div>
	    		<div class="divHora">
					<h3>{!! Form::label('Hora_finaliza', 'Finaliza',
									array('class' => 'control-label')) 
					!!}</h3>
					<div class='input-group date' id='datetimepicker3'>
						{!! Form::text('termina', null,['maxlength'=>'20','minlength'=>'4','class' => 'form-control','id' => 'txt_hora_termina','placeholder'=>'Hora en que termina', 'required'  ])!!}
					    <span class="input-group-addon">
					        <span class="glyphicon glyphicon-time"></span>
					    </span>
					</div>
				</div>
			</div>

			<div class="from-group">
				<h3>{!! Form::label('entrenador', 'Entrenador',
								array('class' => 'control-label')) 
				!!}</h3>
				{!! Form::text('entrenador', null,['class' => 'form-control','id' => 'txt_entrenador','placeholder'=>'Entrenador', 'required' ])!!}
			</div>
			<br/>
			<div class="rowS">
			    <div class="col-md-12 text-left">
					<br />
					<button class="btn btn-primary" id="bt_login">Crear Cita</button>
					<a class="btn" id="bt_cancelar" onclick="cerrarCitaContent()">Cancelar</a>
				</div>
			</div>
			<br/><br/>
	{!! Form::close() !!}
    </div>

<!--Estos javascripts sirben para hacer funcionar al el calendario -->
    <script type="text/javascript" src="{{ asset('/js/calendar/moment.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/calendar/es.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/calendar/bootstrap-datetimepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/calendar/bootstrap-datetimepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/js/cita/cita.js') }}"></script>

gimnasio/resources/views/partials/menu.blade.php
  @if (!Auth::guest())
    <div class="list-group">
      <a href="/medicion/{{$user->id}}" class="list-group-item">Medición de Tallas</a>
      <a href="#" class="list-group-item">Morbi leo risus</a>
      <a href="#" class="list-group-item">Porta ac consectetur ac</a>
      <a href="#" class="list-group-item">Vestibulum at eros</a>
      <a href="#" class="list-group-item">{{Session::get('tipoUsuario')}}</a>
    </div>
  @endif

gimnasio/resources/views/partials/tableUsers.blade.php
 <link href="{{ asset('/css/home_tables_users.css') }}" rel="stylesheet">

<div class="all-content-tables-users">
      <div class="data-tables">
          <div class="search-users">
            {!! Form::open(array('url' => 'getUsersByName','role'=>'form','method' => 'POST','id'=>'txt_form_table_user_busqueda')) !!}
              <input type="search" id="search2" value="" name="nombre"class="form-control" placeholder="Buscar usuario por nombre">
             {!! Form::close() !!}
          </div>

          <div class="col-md-13 col-md-offset-0 div-table-user-inicio">
            <div class="panel-body">
              <table class="table table-striped" id="table">
                <thead>
                  <tr>
                    <th>Avatar</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Correo</th>
                    <th>Cédula</th>
                    <th>Editar</th>
                    <th>Perfil</th>
                  </tr>
                </thead>
                <tbody>
                  <?php foreach ($users as $user): ?>
                    <tr data-id="{{$user->id}}">
                      <td><img src="{{ asset($user->imagen)}}"style="width:50px;height:50px;"></td>
                      <td>{{$user->nombre}}</td>
                      <td>{{$user->apellido1}}</td>
                      <td>{{$user->email}}</td>
                      <td>{{$user->cedula}}</td>
                      <td><a href="{{route('admin.users.edit',$user->id)}}" class="btn btn-primary">Editar</a></td>
                      <td><a href="/perfil/{{$user->id}}" class="btn btn-info">Perfil</a></td>
                  </tr>
                  <?php endforeach; ?>
                </tbody>
              </table>

              <?php echo $users->render(); ?>
            </div>

          </div>

      <div class="col-md-13 col-md-offset-0 div-table-user-busqueda">
      </div>











      </div>
</div>